### ISSUE TITLE
DX improvements

### ISSUE THREAD

**Issue by milancermak** [xJonathanLEI/starknet-rs#53]
While playing around with the lib, I came across a couple of peculiarities listed below. I think tackling them would result in a better developer experience. I'd like to know your opinion @xJonathanLEI, if you think they are worth dealing with.

#### 1) Print out a hash representation of `UnsignedFieldElement` (where it makes sense?):

Take the example from #52 of `dbg!(result);` This prints out something like this:
```
[src/main.rs:59] result = AddTransactionResult {
    code: TransactionReceived,
    transaction_hash: UnsignedFieldElement {
        inner: 2728449641502938754811783899429488071781078345184259994040934169808967186824,
    },
    address: None,
}
```
The issue is I can't copy-paste the transaction hash to [Voyager](https://goerli.voyager.online/) easily, I have to convert it to its hex representation first. Same applies to e.g. `block_hash` in various types. Is there a good solution for this?

#### 2) Build an abstraction over [`AcceptedOnL1` / `AcceptedOnL2`](https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-core/src/types/transaction_receipt.rs#L42-L43).

The idea is to prevent code like this:
```rust
  let tx = provider.get_transaction_status(tx_id).await.unwrap();

    if let TransactionStatus::AcceptedOnL2(b) = tx {
        dbg!(b.block_hash);
    } else if let TransactionStatus::AcceptedOnL1(b) = tx {
        dbg!(b.block_hash);
    }
```
since, normally, a TX gets accepted on L1 eventually, but I might not care when the transition happens. This might be potentially solved by resolving #9.

#### 3) Add `From`/`TryFrom` to streamline `UnsignedFieldElement` conversion
What do you think about implementing `From`/`TryFrom` traits to enable `UnsignedFieldElement::from("0xc0ffee")`, replacing `from_str` and `from_hex_str`? An added benefit is less need for `unwrap`ing. Similarly could be done to replace `try_from_bytes_be` though I don't think that's going to be used so often.

#### 4) Use `BlockId::Latest` instead of `None`
A bunch of provider functions take a `block_identifier: Option<BlockId>` argument. Setting it to `None` implies the latest block (however, only on the gateway level). This results in, subjectively, ugly code:
```rust
account.get_nonce(Some(BlockId::Number(56000))).await.unwrap();
account.get_nonce(None).await.unwrap();
```
For example in Python, I'd define the `get_nonce` function with a default argument `def get_nonce(block_id=None)` so one could do:
```python
account.get_nonce(56000)
account.get_nonce()
```
Is there a way to achieve something similar?

What I thought about is to replace the `None` option with a `BlockId::Latest` enum field. That way, we could remove the `Option`ality of the `block_identifier` and the intention would be clear and explicit: `account.get_nonce(BlockId::Latest).await.unwrap()`. WDYT?

## TODOs:
* [x] Print out a hash representation of `UnsignedFieldElement`
* [x] Use a non-optional `BlockId` in `Provider` trait
* [ ] Have only `from_hex_str` and `from_dec_str` to convert strings to `UnsignedFieldElement`

**Comment by xJonathanLEI** [comment]
Thanks for the feedback! They're solid ideas and we should definitely tackle them (update issue with TODO list?).

However, for item 3 I don't think I understand. If you implement `TryFrom` for strings, you'd still need an `unwrap()`; and if you implement `From` instead, you'd have to panic on invalid input, probably a bad idea. As a developer, I'd want to control panics myself (by choosing to call `unwrap`).

For `try_from_bytes_be` I also don't think that's a good idea. There's something special about conversion to/from byte arrays: endianess. This difference cannot be conveyed to developers if it's implemented as traits.

**Comment by xJonathanLEI** [comment]
For others, I think we certainly should do. In fact, I myself have been considering doing 1 and 4 lol.

**Comment by xJonathanLEI** [comment]
Despite the "not production ready" tag, I've already started using this lib for building services to be used in production. I should also be able to discover some pain points.

**Comment by milancermak** [comment]
Added TODOs for 1) and 4) so far.

**Comment by xJonathanLEI** [comment]
Hmm I see where you're coming from for the 3rd issue. So here's my rationale against it.

1. Generally I tend to avoid _any_ panics in my code. The cost of allowing cleaner code here is potentially surprising developers who didn't realize the code can panic until its live in production (where it accepts real-world user inputs).

2. If we implement `From`, it's literally gonna be calling  `unwrap` on`TryFrom`. Developers can write a utility function for it themselves if they want.

3. Forcing developers to either call `unwrap` or handle errors makes it explicit that the code can fail, not just to developers themselves, but also other developers reading their code.

Personally, I'd rather introduce unsafe undefined behavior for performance reasons (with a big warning on the function name of course) than panicking.

**Comment by xJonathanLEI** [comment]
Actually, I don't even know if having even `from_str` is a good idea. I might as well just remove that and only keep `from_hex_str` and `from_dec_str`. I'd rather have `from_str_radix`.

The reason is that `from_str` can surprise developers too. I was once surprised by the `from_str` behavior of Parity's `U256`, which automatically assumes hex encoding, even when the prefix is not present. I only ever tested my application with numbers lower than 10, where hex/dec doesn't make a difference. That bug slipped into production lol.

The thing is `from_str` (or `From` and `TryFrom`) doesn't inform developers of the encoding being used. It's actually a very similar situation to the byte array endianess problem.

**Comment by milancermak** [comment]
`From` and `TryFrom` are ecosystem standards, people 1) expect them and/or 2) know how to use them and what it entails. If we have both, users can decide if they want to handle errors or have the potentially panicking behaviour. I don't see the drawback of the lib offering both.

I actually like the `from_str` behaviour of Parity's U256 you describe :)

I agree on ditching `from_str` for the two explicit functions `from_hex_str` and `from_dec_str`. What would `from_str_radix` do?

**Comment by xJonathanLEI** [comment]
They are standard traits. But `From` implies that nothing could go wrong. That's why `TryFrom` exists. I don't think it's appropriate to implement `From` when it can indeed go wrong. To make this explicit, developers should be forced to call `unwrap` IMO.

So I do think there's a drawback for offering `From`: it makes it look like it will always succeed.

**Comment by xJonathanLEI** [comment]
For a similar reason, this does _not_ compile:

```rust
let a = u32::from(1u64);
```

Following your argument, the Rust standard library should implement `From<u64>` for `u32` too, for the sake of making it "cleaner" for developers that are certain it's not gonna fail.

But nope, it isn't implemented, because the very present of a `From` implementation implies that an operation will never fail. That's my concern. It goes against the established practice.

**Comment by milancermak** [comment]
That's true 👍 Good point.

**Comment by milancermak** [comment]
Closing this. The proposed improvements have been either already resolved through code or discussion above. 💪
